baseURL = "https://gdlp.co.uk/"
languageCode = "en-gb"
title = "GDLP"
theme="archie"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=4 # articles per page

[params]
	mode="auto" # color-mode â†’ light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "gabrielle de la puente * this is my little blog hello * contact details on the Info page >"

# Social Tags

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/gdlp__"


# Main menu Items

[[menu.main]]
name = "Info"
url = "/info"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3



